// Generated by tools/slice-pieces.js (pnpm assets). Do not edit by hand.
/** Painted piece art, one per game colour. */
export const PIECE_ART: Record<string, number> = {
  blocks: require('../../assets/pieces/blocks.png'),
  chest: require('../../assets/pieces/chest.png'),
  crates: require('../../assets/pieces/crates.png'),
  lasso: require('../../assets/pieces/lasso.png'),
  laurel: require('../../assets/pieces/laurel.png'),
  pyramid: require('../../assets/pieces/pyramid.png'),
  revolvers: require('../../assets/pieces/revolvers.png'),
  rings: require('../../assets/pieces/rings.png'),
  'saloon-doors': require('../../assets/pieces/saloon-doors.png'),
  spur: require('../../assets/pieces/spur.png'),
  sunset: require('../../assets/pieces/sunset.png'),
  target: require('../../assets/pieces/target.png'),
};
