#!/usr/bin/env node
/**
 * Cuts Tony's piece sheets (assets/brand/piece-sheets/*.png, pieces side by side on a
 * transparent background) into one square PNG per piece in assets/pieces/<colorId>.png, and
 * writes src/game/pieceArt.ts so the app knows which colours have raster art. Pieces are found
 * automatically by the transparent gaps between them; SHEETS maps each one, left to right,
 * to a game colour. Add a sheet: drop the PNG in and add a line here. Run via `pnpm assets`.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { Resvg } = require('@resvg/resvg-js');

const ROOT = path.join(__dirname, '..');
const SHEET_DIR = path.join(ROOT, 'assets', 'brand', 'piece-sheets');
const OUT = path.join(ROOT, 'assets', 'pieces');
/** Output size in px: crisp at the largest on-board piece (~60 pt at @3x). */
const SIZE = 192;

/**
 * Sheet file → piece names, in order left to right. `null` marks a piece that is not used
 * (its hue clashes with a chosen one); it is skipped but still counted, so order holds.
 * Names must match colour ids in src/game/constants.ts.
 */
const SHEETS = {
  'sheet-1.png': ['lasso', 'revolvers', 'spur', 'saloon-doors'],
  'sheet-2.png': ['laurel', null /* trophy */, null /* fire star */, null /* mountain */],
  'sheet-3.png': ['chest', null /* nuggets */, null /* key */, null /* safe */],
  'sheet-4.png': ['pyramid', 'rings', null /* diamond */, null /* wand */],
  'sheet-5.png': ['crates', 'blocks', null /* arrows */, 'target'],
  'sheet-6.png': ['sunset', null /* agave */, null /* arch */, null /* moon */],
};

const read = (file) => {
  const [w, h] = execSync(`sips -g pixelWidth -g pixelHeight "${file}"`)
    .toString()
    .match(/\d+$/gm)
    .map(Number);
  const href = `data:image/png;base64,${fs.readFileSync(file).toString('base64')}`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><image href="${href}" width="${w}" height="${h}"/></svg>`;
  return { w, h, href, px: new Resvg(svg).render().pixels };
};

/** Column runs that contain opaque pixels, i.e. one run per piece. */
const findPieces = ({ w, h, px }) => {
  const opaque = (x) => {
    for (let y = 0; y < h; y += 1) if (px[(y * w + x) * 4 + 3] > 40) return true;
    return false;
  };
  const runs = [];
  let start = -1;
  for (let x = 0; x <= w; x += 1) {
    const on = x < w && opaque(x);
    if (on && start < 0) start = x;
    if (!on && start >= 0) {
      if (x - start > 20) runs.push([start, x - 1]);
      start = -1;
    }
  }
  return runs.map(([x0, x1]) => {
    let y0 = h;
    let y1 = 0;
    for (let y = 0; y < h; y += 1) {
      for (let x = x0; x <= x1; x += 1) {
        if (px[(y * w + x) * 4 + 3] > 40) {
          y0 = Math.min(y0, y);
          y1 = Math.max(y1, y);
        }
      }
    }
    return { x0, x1, y0, y1 };
  });
};

fs.mkdirSync(OUT, { recursive: true });
const made = [];
for (const [file, ids] of Object.entries(SHEETS)) {
  const sheet = read(path.join(SHEET_DIR, file));
  const pieces = findPieces(sheet);
  if (pieces.length !== ids.length) {
    throw new Error(`${file}: found ${pieces.length} pieces, expected ${ids.length}`);
  }
  pieces.forEach(({ x0, x1, y0, y1 }, i) => {
    if (!ids[i]) return;
    const side = Math.max(x1 - x0, y1 - y0) + 4;
    const cx = (x0 + x1) / 2;
    const cy = (y0 + y1) / 2;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${cx - side / 2} ${cy - side / 2} ${side} ${side}" width="${SIZE}" height="${SIZE}"><image href="${sheet.href}" width="${sheet.w}" height="${sheet.h}"/></svg>`;
    fs.writeFileSync(path.join(OUT, `${ids[i]}.png`), new Resvg(svg).render().asPng());
    made.push(ids[i]);
    console.log(`wrote assets/pieces/${ids[i]}.png from ${file} #${i + 1}`);
  });
}

const lines = made
  .sort()
  .map((id) => `  '${id}': require('../../assets/pieces/${id}.png'),`)
  .join('\n');
fs.writeFileSync(
  path.join(ROOT, 'src', 'game', 'pieceArt.ts'),
  `// Generated by tools/slice-pieces.js (pnpm assets). Do not edit by hand.\n/** Painted piece art, one per game colour. */\nexport const PIECE_ART: Record<string, number> = {\n${lines}\n};\n`,
);
console.log('wrote src/game/pieceArt.ts');
