import { memo } from 'react';
import { Image } from 'react-native';

/**
 * The outlaw mark: cowboy skull, sheriff hat, revolvers in gloved fists. Generated by
 * `pnpm assets` from assets/brand/outlaw-source.png, the same art the app icon uses.
 */
const MARK = require('../../../assets/brand/outlaw-mark.png');

export const LogoMark = memo(function LogoMark({ size = 72 }: { size?: number }) {
  return (
    <Image
      source={MARK}
      style={{ width: size, height: size }}
      resizeMode="contain"
      accessibilityIgnoresInvertColors
      accessible
      accessibilityLabel="Prismase"
    />
  );
});
